name: Auto Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  create_release:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, ':bookmark: v')"

    steps:
      - name: Extract version from commit message
        id: version
        run: |
          msg="${{ github.event.head_commit.message }}"
          ver=$(echo "$msg" | sed -n 's/.*:bookmark: v\([0-9.]*\).*/\1/p')
          echo "version=$ver" >> "$GITHUB_OUTPUT"

      - name: Validate version
        run: |
          if [ -z "${{ steps.version.outputs.version }}" ]; then
            echo "No version found in commit message."
            exit 1
          fi

          echo "version=$ver" >> "$GITHUB_OUTPUT"

      - name: Generate release notes
        run: |
          LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || true)

          cat > release_notes.md <<'EOF'
          # 🎉 Release Notes

          ## What's New

          EOF

          if [ -n "$LAST_TAG" ]; then
            git log "$LAST_TAG"..HEAD \
              --pretty=format:"* %s" \
              | grep -v ':bookmark: v' >> release_notes.md || true
          else
            git log \
              --pretty=format:"* %s" \
              | grep -v ':bookmark: v' >> release_notes.md || true
          fi

          cat >> release_notes.md <<'EOF'

          ## Support Development
          If you find this integration useful and want to support its development, please consider fueling me with a coffee! Your support helps me dedicate more time to improving the integration and adding new features. Thank you!

          <a href="https://www.buymeacoffee.com/haartrockner" target="_blank"><img src="https://cdn.buymeacoffee.com/buttons/default-yellow.png" alt="Buy Me A Coffee" height="41" width="174"></a>
          EOF

          echo "Generated release notes:"
          cat release_notes.md
      - name: Create Tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          TAG="v${{ steps.version.outputs.version }}"

          if git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "Tag $TAG already exists"
                      else
            git tag "$TAG"
            git push origin "$TAG"
          fi
      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG="v${{ steps.version.outputs.version }}"

          gh release create "$TAG" \
            --target "$GITHUB_SHA" \
            --title "$TAG" \
            --notes-file release_notes.md